apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmachines.infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubevirt
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: KubevirtMachine
    listKind: KubevirtMachineList
    plural: kubevirtmachines
    singular: kubevirtmachine
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                virtualMachineBootstrapCheck:
                  type: object
                  properties:
                    checkStrategy:
                      type: string
                virtualMachineTemplate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                ready:
                  type: boolean
                addresses:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      address:
                        type: string
      subresources:
        status: {}
